# Running Prediction

In [4]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 

In [2]:
# 2 ways we can predict 
# predict()
# precict_proba()

In [5]:
# step 1
df = pd.read_csv('cleanHeartData1.csv')

In [6]:
df.head()

Unnamed: 0  age  sex  chest_pain_type  resting_blood_pressure  cholestoral  \
0           0   52    1                1                     125          212   
1           1   53    1                1                     140          203   
2           2   70    1                1                     145          174   
3           3   61    1                1                     148          203   
4           4   62    0                1                     138          294   

   fasting_blood_sugar  rest_ecg  Max_heart_rate  exercise_induced_angina  \
0                    0         2             168                        0   
1                    1         0             155                        1   
2                    0         2             125                        1   
3                    0         2             161                        0   
4                    1         2             106                        0   

   oldpeak  slope  vessels_colored_by_flourosopy  thalassemia  target  
0      1.0      2                              2            3       0  
1      3.1      1                              0            3       0  
2      2.6      1                              0            3       0  
3      0.0      2                              1            3       0  
4      1.9      0                              3            1       0

In [7]:
df= df.drop('Unnamed: 0' , axis=1)

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.shape

(302, 14)

In [8]:
# split data
x = df.drop('target',axis=1)
y = df['target']

In [9]:
# chosing ml model and spliting data in test train
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

clf = RandomForestClassifier()
model = clf.fit(x_train,y_train)

model.score(x_test,y_test)

0.8461538461538461

In [10]:
# evaluation model
y_predicted = model.predict(x_test)
y_predicted

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1], dtype=int64)

In [11]:
np.array(y_test)   # groud reality

array([1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1], dtype=int64)

In [12]:
# Method 1
np.mean(y_predicted == y_test)

0.8461538461538461

In [13]:
# Method 2
model.score(x_test,y_test)

0.8461538461538461

In [14]:
# Method 3
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predicted)

0.8461538461538461

# predict_proba()

In [15]:
model.predict(x_test)[:5]

array([1, 0, 1, 1, 1], dtype=int64)

In [16]:
model.predict_proba(x_test)[:5]

array([[0.03, 0.97],
       [0.94, 0.06],
       [0.31, 0.69],
       [0.13, 0.87],
       [0.01, 0.99]])

In [2]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [3]:
df = pd.DataFrame(housing.data, columns=housing.feature_names)
df['target'] = housing['target']
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [28]:
df.shape

(20640, 9)

In [29]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

x = df.drop('target',axis=1)
y = df['target']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

rfr = RandomForestRegressor()
model = rfr.fit(x_train,y_train)

model.score(x_test,y_test)

0.8015720282946912

In [30]:
# make predicton 
predicted_y = model.predict(x_test)
predicted_y[:5]

array([3.5148006, 0.9651   , 2.54313  , 2.58031  , 2.0883801])

In [31]:
np.array(y_test)[:5]

array([4.85 , 0.726, 2.762, 2.835, 2.71 ])

In [32]:
# compare the prediction with groud reality
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,predicted_y)

0.3352495790697676

# Evaluation Machine learning Model#
### 1.Estimator Score Method
### 2.The scoring parameters
### 3.Problem-specific metic Fundtion

In [33]:
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [42]:
from sklearn.ensemble import RandomForestClassifier
np.random.seed()

x = df.drop('target',axis=1)
y = df['target']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

rfc = RandomForestClassifier()
model = rfc.fit(x_train,y_train)

model.score(x_test,y_test)

1.0

In [43]:
model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [44]:
model.score(x_train,y_train)

1.0

In [45]:
model.score(x_test,y_test)

1.0

In [46]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
np.random.seed()

x = df.drop('target',axis=1)
y = df['target']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

model =  RandomForestRegressor().fit(x_train,y_train)

model.score(x_test,y_test)

0.9003080851470027

In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
np.random.seed()

x = df.drop('target',axis=1) # using heart disease data
y = df['target']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

model =  RandomForestClassifier().fit(x_train,y_train)

model.score(x_test,y_test)

0.819672131147541

In [12]:
model.score(x_test,y_test) # normal score method

0.819672131147541

In [11]:
from sklearn.model_selection import cross_val_score
cross_val_score(model,x,y,cv=5)

array([0.86885246, 0.81967213, 0.9       , 0.78333333, 0.76666667])

In [15]:
np.mean(cross_val_score(model,x,y,cv=5)),model.score(x_test,y_test)

(0.8343169398907104, 0.819672131147541)

# Classification Model Evaluation
# Accuracy
# Area Under the Curve ROC
# Confussion Matrix
# Classification report


## Accuracy:

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
np.random.seed()

x = df.drop('target',axis=1) # using heart disease data
y = df['target']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

model =  RandomForestClassifier().fit(x_train,y_train)

model.score(x_test,y_test)

from sklearn.model_selection import cross_val_score
np.mean(cross_val_score(model, x,y , cv = 5 , scoring= None))

0.8178142076502732

In [21]:
print(f"Cross Validation Accuracy : {np.mean(cross_val_score(model, x,y , cv = 5 ))*100:.2f}%")

Cross Validation Accuracy : 81.78%


In [25]:
#create test train data 
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

from sklearn.metrics import roc_curve

x = df.drop('target',axis=1) # using heart disease data
y = df['target']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

clf = RandomForestClassifier()
model = clf.fit(x_train,y_train)

y_probab = clf.predict_proba(x_test)

In [31]:
y_probab_p = y_probab[:,1], y_test[:5]

In [30]:
# True positive :  Truth  = 1  , Model = 1
# False positive :  Truth  = 0  , Model = 1
# True negitive :  Truth  = 0  , Model = 0
# False negitive :  Truth  = 1  , Model = 0

In [35]:
# calculate fpr , tpr , threshold : 
fpr, tpr, threshold = roc_curve(y_test, y_probab_p)

In [36]:
fpr

array([0.        , 0.        , 0.        , 0.06060606, 0.06060606,
       0.06060606, 0.06060606, 0.12121212, 0.12121212, 0.15151515,
       0.18181818, 0.18181818, 0.21212121, 0.24242424, 0.24242424,
       0.3030303 , 0.42424242, 0.45454545, 0.48484848, 0.48484848,
       0.54545455, 0.57575758, 0.60606061, 0.66666667, 0.78787879,
       0.84848485, 0.87878788, 0.93939394, 1.        ])