In [1]:
import numpy as np

### Data Types

Array

In [8]:
#1d array / vector
a1d = np.array([1,2,3])

In [3]:
a1d

array([1, 2, 3])

In [28]:
#2d array / Matrix
a2d = np.array([[1,2,3],[4,5,6]])

In [5]:
a2d

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
#3d array 
a3d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [7]:
a3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [11]:
a1d.shape

(3,)

In [12]:
a2d.shape

(2, 3)

In [14]:
a3d.shape

(2, 2, 3)

# Important Functions in Array

In [15]:
a3d.shape

(2, 2, 3)

In [17]:
a3d.ndim # tell dimensions

3

In [19]:
a3d.dtype

dtype('int32')

In [20]:
a3d.size

12

In [21]:
type(a3d)

numpy.ndarray

In [22]:
import pandas as pd

In [23]:
df = pd.DataFrame(a2d)

In [24]:
df

0  1  2
0  1  2  3
1  4  5  6

# Creating numpy Array

In [25]:
test_array = np.array([1,2,3])

In [28]:
test_array

array([1, 2, 3])

In [41]:
# Zeros
# Ones
# randomes
ones = np.ones((2,3))

In [42]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
ones.dtype

dtype('float64')

In [43]:
zeros = np.zeros((2,3))

In [44]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
range_array = np.arange(0,20,2) # (start,stop,step size)

In [4]:
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [49]:
random_matrix = np.random.randint(0,10,size = (3,5))  #(start,stiop ,size)

In [57]:
random_matrix  #manual range

array([[4, 9, 2, 2, 2],
       [2, 8, 4, 2, 0],
       [0, 4, 7, 1, 2]])

In [51]:
random_matrix.shape

(3, 5)

In [52]:
random_matrix.size

15

In [55]:
rand_matrix = np.random.rand(3,5)  #auto range 0-1

In [56]:
rand_matrix

array([[0.27150494, 0.05545333, 0.13025804, 0.66649165, 0.71599314],
       [0.48955916, 0.78094925, 0.89494257, 0.92279634, 0.16269352],
       [0.6989043 , 0.02655472, 0.88577737, 0.62357004, 0.7702985 ]])

### Seed 

In [25]:
rand_matrix = np.random.rand(3,5)

In [26]:
rand_matrix.sum()

7.775560214726889

to fix this changing this random int we will do below work

In [21]:
np.random.seed(seed = 0)
rand_matrix = np.random.rand(3,5)

In [22]:
rand_matrix.sum()

9.042960048565472

## Accessing Elements

In [29]:
a3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [30]:
a2d

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
a2d[0]

array([1, 2, 3])

In [32]:
a2d[1]

array([4, 5, 6])

In [33]:
a3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [34]:
a3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
a3d[1]

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
a3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [46]:
a3d[0:2,0:1,0:2] # slicing a 3d matrix
# 0:2  take from 0 to 2( mean both above 2d matrix )
# 0:1  takes from 0 to 1( means from each matrix take only one element)
# 0:2  take from zero to 2 ( means column 0 to 2)

array([[[1, 2]],

       [[1, 2]]])

In [1]:
import numpy as np
arandom = np.random.randint(10, size= (3,4,5))

In [2]:
arandom

array([[[6, 5, 0, 1, 3],
        [3, 5, 2, 0, 1],
        [2, 1, 6, 1, 1],
        [9, 1, 8, 4, 2]],

       [[7, 9, 1, 7, 2],
        [9, 6, 7, 0, 5],
        [0, 8, 0, 8, 6],
        [3, 8, 8, 2, 3]],

       [[1, 0, 7, 5, 2],
        [2, 0, 2, 2, 2],
        [4, 5, 7, 9, 3],
        [6, 3, 8, 6, 3]]])

In [5]:
arandom[1:2,1:3,1:3]

array([[[6, 7],
        [8, 0]]])

In [56]:
arandom = np.random.randint(10, size= (2,3,4,5))

In [58]:
arandom

array([[[[5, 5, 0, 8, 1],
         [1, 0, 3, 8, 8],
         [4, 4, 0, 9, 3],
         [7, 3, 2, 1, 1]],

        [[2, 1, 4, 2, 5],
         [5, 5, 2, 5, 7],
         [7, 6, 1, 6, 7],
         [2, 3, 1, 9, 5]],

        [[9, 9, 2, 0, 9],
         [1, 9, 0, 6, 0],
         [4, 8, 4, 3, 3],
         [8, 8, 7, 0, 3]]],


       [[[8, 7, 7, 1, 8],
         [4, 7, 0, 4, 9],
         [0, 6, 4, 2, 4],
         [6, 3, 3, 7, 8]],

        [[5, 0, 8, 5, 4],
         [7, 4, 1, 3, 3],
         [9, 2, 5, 2, 3],
         [5, 7, 2, 7, 1]],

        [[6, 5, 0, 0, 3],
         [1, 9, 9, 6, 6],
         [7, 8, 8, 7, 0],
         [8, 6, 8, 9, 8]]]])

In [62]:
arandom[:1,:1,0:1,:1]

array([[[[5]]]])

# Array Mainpulation

In [2]:
a1d = np.array([1,2,3])

In [3]:
ones = np.ones((2,3))

In [4]:
a1d

array([1, 2, 3])

In [5]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
a1d + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

### maping or broadcasting

In [7]:
a1d - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [8]:
a2d = np.random.randint(0,10,size = (2,3))

In [9]:
a2d

array([[3, 6, 8],
       [7, 0, 7]])

In [12]:
a3d = np.random.randint(0,10, size = (2,2,4))

In [13]:
a3d

array([[[8, 5, 9, 9],
        [3, 2, 0, 6]],

       [[0, 6, 8, 2],
        [4, 8, 3, 0]]])

In [17]:
t = a3d[:2,:2,:3]

In [20]:
a2d + t

array([[[11, 11, 17],
        [10,  2,  7]],

       [[ 3, 12, 16],
        [11,  8, 10]]])

In [24]:
a1d // a2d

C:\Users\AL Rehman Computer\AppData\Local\Temp\ipykernel_14088\3014494431.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  a1d // a2d


array([[0, 0, 0],
       [0, 0, 0]])

In [25]:
np.square(a1d)

array([1, 4, 9])

In [26]:
 a1d + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [27]:
np.add(a1d,ones)

array([[2., 3., 4.],
       [2., 3., 4.]])

In [28]:
a2d % 2

array([[1, 0, 0],
       [1, 0, 1]], dtype=int32)

# Agregation

In [2]:
a1d  #matrix

NameError: name 'a1d' is not defined

In [35]:
sum(a1d)     # this is python method , slow method

6

In [36]:
np.sum(a1d)  # this is python method , fast method

6

In [48]:
array = np.random.random(10000)

In [49]:
array

array([0.36410551, 0.79908804, 0.53190906, ..., 0.1847571 , 0.6055804 ,
       0.93464506])

In [50]:
array.size

10000

In [53]:
%timeit sum(array)       #python sum
%timeit np.sum(array)    #np sum

3.26 ms ± 780 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
25.9 μs ± 6.44 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [54]:
np.max(a1d)

3

In [55]:
np.min(a1d)

1

In [56]:
#mean
#standard daviation
#varience

In [5]:
a1d = np.array([1,2,3])

In [6]:
a1d

array([1, 2, 3])

In [8]:
np.var(a1d)

0.6666666666666666

In [9]:
np.mean(a1d)

2.0

In [15]:
np.sqrt(np.var(a1d)) # standard deviation manually 

0.816496580927726

In [16]:
np.std(a1d)     # standard deviation function

0.816496580927726